version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/scrumify-app

    steps:
      - checkout
      - run:
          name: build frontend
          command: |
            cd frontend
            npm install
            npm run build

      - run:
          name: build backend
          command: |
            cd backend
            npm install
            npm run build-ts

          